In [3]:
import numpy as np

In [7]:
#create 1D array
a= np.array([1,2,3,4,5])
b= np.array([2,4,6,8,10])

print(a)
print(b)


[1 2 3 4 5]
[ 2  4  6  8 10]


In [8]:
print(a+b)
print(a-b)
print(a*b)


[ 3  6  9 12 15]
[-1 -2 -3 -4 -5]
[ 2  8 18 32 50]


In [10]:
n2=np.array([[1,2],[4,9]]) # 2x2 matrix
print(n2)

[[1 2]
 [4 9]]


In [17]:
n3=np.array([[1,3],[2,6],[5,12]])
print(n3)

[[ 1  3]
 [ 2  6]
 [ 5 12]]


In [20]:
print(n3.shape)
print(n3.ndim)
print(n3.dtype)

(3, 2)
2
int64


In [26]:
print(np.arange(1,100,5))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [9]:
print(np.random.randint(1,10,size=(2,3))) #picks random integer from 1-10 in 2x3 matrix 

[[5 9 7]
 [2 6 9]]


In [10]:
a1=np.array([[1,2,3],[4,5,7],[1,9,7]])
a2= np.array([[2,4,8],[3,4,5],[1,2,4]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 7]
 [1 9 7]]
[[2 4 8]
 [3 4 5]
 [1 2 4]]


In [43]:
print(a1*a2) #element wise multiplication
print(a1@a2) #matrix dot product
print (a1.prod()) #product of all elements of a1
print(a1.mean()) #mean of all elements of a1
print(a1.mean(axis=0)) 
print(a1.min(axis=1))

[[ 2  8 24]
 [12 20 35]
 [ 1 18 28]]
[[11 18 30]
 [30 50 85]
 [36 54 81]]
52920
4.333333333333333
[2.         5.33333333 5.66666667]
[1 4 1]


In [46]:
# mathematical functions
print(a1.sum()) #addition
print(a1.std()) #standard deviation
print(a1.var()) #variance

39
2.70801280154532
7.333333333333333


In [47]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50)) #median
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,75)) #3rd quartile

5.0
3.0
7.0


In [11]:
import numpy as np
print(np.unique(a1))

[1 2 3 4 5 7 9]


In [12]:
a=np.random.randint(1,100,(4,4))
print(a)
print('2x8')
print(a.reshape(2,8))

[[37 65 35 28]
 [46 41 15 16]
 [ 7 73  5 65]
 [86 48 12 64]]
2x8
[[37 65 35 28 46 41 15 16]
 [ 7 73  5 65 86 48 12 64]]


In [13]:
x=np.random.randint(1,10,(5,5))
print(x)

[[4 6 1 9 3]
 [4 7 7 4 2]
 [2 9 4 3 1]
 [7 2 1 4 4]
 [6 1 3 9 3]]
